### PR TITLE
Issue765 rmc.desiredtz and rmc.configtz

### LINKED ISSUE #765: Replace rmc.desiredtz and rmc.configtz
Having arguments `rmc.desiredtz` and `rmc.configtz` is confusing given that we also have argument `desiredtz` and `configtz`.

**Proposal for now:**
- [x] Add code to detect when `rmc.desiredtz` or `rmc.configtz` are specified and internally use them to overwrite `desiredtz` or `configtz` as part of the `check_params` and inside function `read.myacc.csv`.
- [x] Warn user inside `check_params` and inside `read.myacc.csv` when this happens.
- [x] Update documentation for `rmc.desiredtz` and `rmc.configtz` to state that these are scheduled for deprecation, and that user should start using `desiredtz` and `configtz` instead.

**Proposal for after deprecation:**
- [ ] When they are fully deprecated, keep trying to detect whether user specifies  `rmc.desiredtz` and `rmc.configtz`  and create error to inform them that these arguments were deprecated.

### PR DESCRIPTION
**Pull request by jhmigueles**
Fixes #765 => If defined by the user, `rmc.desiredtz` and `rmc.configtz` are used to overwrite desiredtz and configtz and a warning is provided announcing that the rmc versions will be deprecated soon.

Checklist before merging:

- [x] Existing tests still work (check by running the test suite, e.g. from RStudio).
- [x] Added tests (if you added functionality) or fixed existing test (if you fixed a bug).
- [x] Updated or expanded the documentation.
- [x] Updated release notes in `inst/NEWS.Rd` with a user-readable summary. Please, include references to relevant issues or PR discussions.
- [ ] Added your name to the contributors lists in the `DESCRIPTION` and `CITATION.cff` files.

### CODE REVIEW

**Review by vincentvanhees — CHANGES_REQUESTED** [review]
Hi Jairo, I think this solutation is too complex. You announce that the arguments will be deprecated and advise to use the other arguments. But in this PR the functionality has already changed because `rmc.desiredtz` is used to overwrite `desiredtz`. So, if the user specifies `desiredtz` and `rmc.desiredtz` by accident (e.g. because it was in the config file) we risk that code will still use the wrong value even though the user has started using `desiredtz`. I think this becomes too complex to oversee.

Proposal:
- Do all corrections and warnings in `read.myacc.csv` and not in `check_params` because `read.myacc.csv` is always used when working with ad-hoc csv data even when testing the input arguments as we encourage people to do in the vignette.
- Add arguments `desiredtz` and `configtz` to `read.myacc.csv` with function default NULL, even though their defaults in `load_params` are different, this is intentional.
- Change `load_params` default of `rmc.desiredtz` and `rmc.configtz` to NULL, such that it is easy to detect later on whether the user with the R script or the config file changed these defaults.
- Next, add code to check inside `read.myacc.csv`: 
  - If `rmc.desiredtz` is not NULL give warning, because this indicates that user is specifying `rmc.desiredtz`. Further, use the value to overwrite `desiredtz`.
  - Same for `rmc.configtz`.
  - If `desiredtz` is NULL give error that `desiredtz` needs to be provided.
  - Same for `configtz`.

**Comment by vincentvanhees** [comment]
Also I noticed that in the parameters vignette the default of "" is not clearly shown:

image

It only shows one part of the quotes ". Maybe good to also try to fix that.

**Comment by jhmigueles** [comment]
> Also I noticed that in the parameters vignette the default of "" is not clearly shown:
> 
> image
> 
> It only shows one part of the quotes ". Maybe good to also try to fix that.

I think this is because it uses single quotes instead of double quotes (although I see they are both closing quotes). In the function documentation it is correct, and this is only a copy of the function documentation as stated at the beginning of section 2 of the vignette. So I'm not sure if this can be fixed, do you have any proposal?

**Comment by jhmigueles** [comment]
Thanks for the revision and suggestions! I think I applied all your suggested changes. The warnings/errors are moved to `read.myacc.csv` function and the default values are changed as you suggested. In brief, the warnings/errors logic is:

- If user specifies `desiredtz` but not `rmc.desiredtz` -> no warning/error
- If user specifies `rmc.desiredtz` but not `desiredtz` -> warning and `rmc.desiredtz` used to overwrite `desiredtz`
- If user specifies `desiredtz `AND `rmc.desiredtz` and they are different -> error as GGIR cannot know which one to use
- If user specifies `desiredtz` AND `rmc.desiredtz` and they are equal -> warning to tell the user to only use `desiredtz`
- Same logic applied to `configtz` and `rmc.configtz`
- If both `rmc.desiredtz` and `desiredtz` are NULL -> error, user needs to specify at least one (very unlikely as `desiredtz` default configuration is "")

The only pending change is the one in the vignette which I'm not sure how to fix.

**Comment by vincentvanhees** [comment]
@jhmigueles sorry, my message may not be clear, when I wrote:

> So, I think it is easier for now to limit the update to the read.myacc.csv changes only.

What I meant to say is, please revert these changes to `g.readaccfile`, `g.calibrate`, and `g.inspectfile`:

image

image

image

**Comment by jhmigueles** [comment]
> This seems to be caused by [these](https://github.com/wadpac/GGIR/blob/f70f3cebf72f5414a137daddfdb8c3bfe3ccee57/R/ShellDoc2Vignette.R#L70-L71) lines in ShellDoc2Vignette, which replaces all double quotes by single quotes. When I comment them out the vignette is rendered correctly with double quotes for all character arguments.
Do you remember why you had this conversion included, can we remove it?

I think I did this in order to keep consistency in the use of quotes in the vignette. I have been looking at the vignette after commenting this out and I can't find anything wrong. I would leave this commented out for now, just in case we find something wrong later on we can go easily back. Are you ok with this?

**Comment by vincentvanhees** [comment]
> I would leave this commented out for now, just in case we find something wrong later on we can go easily back. Are you ok with this?

Sounds good. I agree that consistency is good but function argument defaults are the exception because they in the first place need to be consistent with the function defaults.

**Review by vincentvanhees — APPROVED** [review]
Looks good, I have now simplified the code for the warnings in `read.myacc.csv()`.

Also, I rephrased some of the warning and error messages, and I removed line breaks "\n". I think we should not do this because it introduces the risk that people miss the second half of a warning. Instead I prefer concise single sentence warnings.

For console messages with cat() this is a different story, because those are often intended to be readable as a multi-line message.

I will merge the PR when tests have passed.

**Pull request merged**
