### PR TITLE
Update branch to master

### PR DESCRIPTION
**Pull request by jhmigueles**

### CODE REVIEW

**Comment by vincentvanhees** [comment]
@jhmigueles the master branch is now broken, can you please fix this?

**Comment by vincentvanhees** [comment]
or did this problem already exists before you made the commit?

**Comment by jhmigueles** [comment]
I think so, I only commited from master to the issue352 branch to update my branch before making a pull request. But I didn't commited anything to the master branch. Let me know if I did anything wrong or if I should fix anything.

**Comment by vincentvanhees** [comment]
Ok, I am now investigating what the problem is with the master branch. It all worked yesterday.

**Comment by vincentvanhees** [comment]
I think everything is fine, and it just a glitch in AppVeyor, I suspect that when we make a new change to the master branch the error will disappear.

**Pull request merged**
