### PR TITLE
Issue352 includeddays

### PR DESCRIPTION
**Pull request by jhmigueles**
I found that the MM personSummary output skips the last days of measurement when the data recording starts with some days of non-wear. In g.part5, line 351, the Nwindows definition for "MM" was the number of nights included in the nightsummary of part 4. This included the first non-wear days and then stopped before than expected. Now, I have re-defined the Nwindows as in the "WW" report plus one extra day to account for differences between timewindows.

### CODE REVIEW

**Review by vincentvanhees — CHANGES_REQUESTED** [review]
Hi Jairo, The pull request has a merge conflict, probably it struggles to merge DESCRIPTION and/or NEWS.Rd file. Can you fix?
Looks good otherwise. May I assume that you checked that the sleep estimates for the last day and the duration of the last date are correct?

**Comment by jhmigueles** [comment]
I have now double-checked the last day time window definition and sleep estimates. They are coherent with part 4. I had to change the reference to define qqq windows from summarysleep not to skip the last days of measurement in g.part5.definedays

**Comment by vincentvanhees** [comment]
I may need a bit more time for this. The changes also affect WW window results and I want to make sure that those analysis are not suddenly resulting in all kinds of issue.

**Comment by jhmigueles** [comment]
Really? I got the exact same values in my files. Thanks, I will double check the changes just in case.

**Comment by vincentvanhees** [comment]
I did not say that they affect the results, but they affect the code involved in WW calculation. So, in theory they could affect the WW results. This is why I am now investigating this carefully as it took a lot of work earlier this year to get the WW analysis to work across a wide range of data conditions.

**Comment by vincentvanhees** [comment]
Hi Jairo, looks good. I have run some test analysis and everything seems to work.

I only made one edit to the new code in g/part5.wakesleepwindows.R because you cannot have a check for length and a check of is.na in the same if statement. If object has length zero then is.na is impossible and will not be able to return a boolean.

**Review by vincentvanhees — APPROVED** [review]

**Pull request merged**
