### PR TITLE
Allow for specifying desiredtz and configtz when working with gt3x files

### LINKED ISSUE #551: Argument configtz and desiredtz not used for .gt3x data
It seems that argument configtz and desiredtz are not used when reading .gt3x data. The code seems to default to local timezone.
I am now investigating and proposing a solution.

### PR DESCRIPTION
**Pull request by vincentvanhees**
fixes #551 

For .gt3x data files we did not account for arguments `desiredtz` or `configtz`, and it defaulted to the local timezone where GGIR was run. With this PR this should be addressed.

I have tested the new functionality with example files from a study in the USA where we know in which timezone the files were configured and in which timezone the accelerometer was worn.

Checklist before merging:

- [x] Existing tests still work (check by running the test suite, e.g. from RStudio).
- [x] Added tests (if you added functionality) or fixed existing test (if you fixed a bug).
- [x] Updated or expanded the documentation.
- [x] Updated release notes in `inst/NEWS.Rd` with a user-readable summary. Please, include references to relevant issues or PR discussions.
- [ ] Added your name to the contributors lists in the `DESCRIPTION` and `CITATION.cff` files.

### CODE REVIEW

**Comment by vincentvanhees** [comment]
@jhmigueles Do you have time in the upcoming week to review and test this PR?  I think it does the job, but given that this is an important update for gt3x users it may be good if you could also check it out.

**Review by jhmigueles — COMMENTED** [review]
I have had some fun testing this branch and it all looks good to me. I have made some tests using different actigraph files, both in gt3x and csv, and the configtz and desiredtz work as expected. My only comment is on the g.shell.GGIR documentation where it is specified that desiredtz and configtz is only functional for AX3 cwa and Actigraph gt3x (it is also working, at least with Actigraph csv files).

**Comment by vincentvanhees** [comment]
thanks Jairo, I am also looking into the timegaps/timeleaking behaviour reported by Youngdeok.
I suspect that the changes to the timestamp format impact on the behaviour of the g.imputeTimegaps.R function.
I am now experimenting with changing the minimum timegap to be impute (k)... will let you know when I have results.

**Comment by vincentvanhees** [comment]
... I think I fixed it, will commit fix in a couple of minutes. Now updating unit-tests.

**Comment by vincentvanhees** [comment]
>  My only comment is on the g.shell.GGIR documentation where it is specified that desiredtz and configtz is only functional for AX3 cwa and Actigraph gt3x (it is also working, at least with Actigraph csv files).

Thanks, this is now addressed.

**Comment by vincentvanhees** [comment]
I will close this PR now, because I think I fixed the issues in a separate branch and will create a new PR for that later today.

**Pull request closed without merging**
