### PR TITLE
Release2.1 0

### PR DESCRIPTION
**Pull request by vincentvanhees**
My plan is to create a new CRAN + GitHub release, based on the GitHub-only releases 2.0-1 and 2.02. In addition this pull requests adds to that:

- Actigraph serial number now extracted from the csv fileheader
- Actigraph serial number now used to assign correct dynamic range per
- Actigraph generation (6 and 8 g respectively). Previously 8 assumed.
- Actigraph - bug fixed with Actigraph starttime recognition when machine language is not English and months are expressed in b or hh format.
- Part 2 indicator added of which axis is most correlated with itself
  over 24 hours, for hip data this may be indicator of vertical axis orientation. Not sure whether this is useful for wrist.
- Part 1 bug fixed in timestamp generation that caused measurements  that start exactly at the hour and 0 minutes to have a 1 minute offset in time.
- Part 1 to reduce data storage size epoch level metric values are now rounded to 4 decimal places.
- Part 4 report, issue fixed with double night entries.
- Unit tests expanded such that test coverage has now gone up from 71 to 75%. There is a more work to be done on improving test coverage, but will save that for future release.

### CODE REVIEW

**Comment by vincentvanhees** [comment]
Additionally, I have now updated my e-mail address in all documentation files and I have added a link to Shimmer/Matt's step count to the package vignette for External function embedding.

**Comment by m-patterson** [comment]
This release runs well on my local test bench of files (other than issue #333, which might only be a local issue to me).

**Comment by jhmigueles** [comment]
The branck works well for me. Tested it in some actigraph files and got the serial numbers correctly.

**Comment by vincentvanhees** [comment]
Thanks both, I just noticed that there was an issue with part 5 when using MM day windows and when the recording starts at exactly midnight. When the code tried to identify the indices for the days (values of qqq object) it considered value 1 to value 1 to be the first day because midnight is directly the first value in the data. This results in a double entry for the first calendar date. I have now made a couple of commits that should have fixed this.

Also I responded to #333.

**Pull request merged**
