### PR TITLE
fix plot5 viewingwindow error

### PR DESCRIPTION
**Pull request by m-patterson**
plot5 function works properly with midnight centered plots (viewingwindow = 2)

- sleep / wake plot annotations are now working properly
- date label is corrected on first day if there is less than 12hr worth of data
- date is the date at the start of the plot

### CODE REVIEW

**Comment by vincentvanhees** [comment]
Thanks Matt

**Comment by m-patterson** [comment]
Sorry for all that commit history being included in this branch. I'm not sure why, I think it is due to how I am updating my fork. I'll look into it and try to rectify for the future.

**Comment by vincentvanhees** [comment]
Hi Matt, the reason for the large commit history is because of https://github.com/wadpac/GGIR/issues/309
I did not realise that if I clean up the mean repository history, your fork does not automatically take over those changes. Hopefully the instruction in the issue I created today will clarify what to do.

**Comment by m-patterson** [comment]
Hi Vincent, I saw your email on the subject, so I'll perform one of those options to update my fork next time. Git doesn't make it easy to keep a clean forked branch. Thanks for the information.

**Pull request merged**
