### PR TITLE
Update g.part5.R

### PR DESCRIPTION
**Pull request by jhmigueles**
Issue #81

### CODE REVIEW

**Comment by vincentvanhees** [comment]
Hi Jairo, this will take me a bit more time to investigate. Your changes to the qqq object seem to make that the code cannot produce the MM window results anymore, it only calculates the WW window results. Note that I am using timewindow = c("WW","MM"), as argument to g.shell.GGIR. I will look at it again tomorrow.

I created the following branch within wadpac:**https://github.com/wadpac/GGIR/tree/pull_82** from your pull request. You have admin rights within wadpac/GGIR so you should be able to work with it.
Cheers, Vincent

**Comment by jhmigueles** [comment]
Sorry Vincent, I have looked at it and I found the problem, I forgot to include a couple of lines in the code with the window information, it seems like it is solved now.
Best,
Jairo

**Comment by vincentvanhees** [comment]
Hi Jairo, thanks for fixing that.

My proposal is to remove the MM option.

In part4_nightsummary_sleep_cleaned.csv each row corresponds to the night that starts on one date and ends on the next date. If sleep onset is before midnight and waking time is after midnight then those timestamps corresponds to different days in the measurement. I only report the date on which the night starts, but it actually reflects a night between two dates.

In part5_daysummary_WW_... .csv we want the same as in part4, because this a day window is now defined from waking up in the morning till waking up the next morning. Note that the first waking up time is not in this row of results, but the second one at the end of the window is. So, the results should be similar to part4. If people want to know at what time the day started they should look at the waking time of the previous row.

In part5_daysummary_MM_... .csv the situation is different. At least that was my intention when I implemented it, but I am not sure now whether it ever worked correctly. In the MM window the day runs from midnight to midnight. So, waking up time and onset time correspond to the same calendar date. When describing sleep we add up the sleep hours at the beginning of the day to the sleep hours in the evening. This is maybe not intuitive from a sleep research perspective, but it allows for expressing time spent in various intensity and behavioral categories per standard 24 hour window.

At the moment the sleep onset and waking times are the same for part4, part5WW and part5MM, which indicates that part5MM probably does not do what it is supposed to do. Further, I noticed that in part MM the before last day is now missing.

Originally I tried to facilitate both MM and WW because I did not knew what window definition would be most interesting for users. WW would provide non-constant window lengths, while MM would provide a standard 24 hour window.

Could it be that WW output is just enough and that we can remove the MM output? We could argue that if people want to have normalise results they could calculate the ratio of time spent in categories relative to day length or relative to waking hours? Do you know whether the compositional data analysis community has any preference on whether to work with WW or MM windows?

If you agree, then my proposal would be to remove the MM option. This will simplify the R code and make it easier for new users to work with. What do you think?

My impression is that WW output looks good, but I will spend a bit more time critically going through it.
Best, Vincent

**Comment by vincentvanhees** [comment]
hi @trucci32 I am tagging you here because maybe you also have an opinion on this topic. We are discussing whether part5 output should only present results for day windows defined from waking in the morning till waking the next morning (WW) or whether it is important that we also have results for days defined from midnight to midnight (MM). I think researchers are used to think in terms of calendar dates, but now we have detailed sleep results too it seems to make much more sense to focus on WW window results.

**Comment by sevslb** [comment]
Dear all

my feeling is that MM will be useful for compositional data analysis where we need to have the sum of all duration to equal a constant for everyone: https://www.ncbi.nlm.nih.gov/pubmed/?term=compositional+data+analysis+and+Dumuid

I did not go far enough to be 100% sure, but I guess we will have to test the method both with MM and WW windows

What do the others think?

Best

**Comment by vincentvanhees** [comment]
Ok, thanks Séverine. I will start investigating how we can make sure that the MM variables are correct in the proposed update to GGIR

**Comment by vincentvanhees** [comment]
For composition data analysis you could normalise the time spent as a fraction of the total per day, so I think the WW window could also facilitate compositional data analysis.

Nonetheless, I think I have identified the problem with the MM window and will commit my changes in a couple of minutes.

**Comment by sevslb** [comment]
You are right, normalization to 24h of the WW window could be a good option as it will have the advantage to keep the natural timing of the diurnal period

**Comment by jmkurka83** [comment]
Hi all,
This is a great discussion and one that corresponds to behavior analyses as well. It's common for physical activity behaviors to be analyzed within a calendar date (midnight-midnight) but obviously sleep behaviors are better analyzed using the WW. Some of my colleagues in the physical activity behavior community are used to seeing part5MM, but would want the sleep periods removed. So, from a health behavioral standpoint, the MM would be easily translatable.

**Comment by vincentvanhees** [comment]
@jmkurka83 thanks for sharing your thoughts, so it sounds to me that facilitating both MM and WW is important.

@jhmigueles - In branch [pull_82](https://github.com/wadpac/GGIR/tree/pull_82) I have modified the code from your pull request to:

* Assign the correct onset and waking time to the MM window which are now date and not night specific.
* Further, I made sure it now extracts the first and last day of a measurement for the MM setting. The results for the WW setting were correct as far as I could see. 
* I have added an argument excludefirstlast.part5 to handle whether the first and last day should be excluded if a user does not want this information in the csv reports. The earlier idea to re-use excludefirstlast (originally included for g.part4) did not work: A user may still want the first and last night, but not the first and last day.

One outstanding bit of work is to look at variable names in the MM setting. My impression is that a couple of them are not intuitive anymore. For example, sleeplog.used or night number: They are specific to a single night, but MM has data from two nights. I will create an issue from this, such that we can have a look at it some other time. Possibly this is something we can address with a separate variable dictionary.

I will now:
* merge these changes into the GGIR master branch
* prepare a new release of the package such that users can start testing it.
* close this pull request

**Pull request closed without merging**
