### PR TITLE
Contributing guidelines (github.io)

### LINKED ISSUE #923: Expand contributing.md with github.io guidelines
Add guidance on how to expand github.io content and make github.io updates to https://github.com/wadpac/GGIR/blob/master/CONTRIBUTING.md #27

### PR DESCRIPTION
**Pull request by jhmigueles**
Closes #923 => Adds contributing guidelines for github.io. This branch also updates the information in the github.io webpage, which still stated the GGIR version 2.9-5 (I did this to make sure the contributing guidelines were precise).

Checklist before merging:

- [x] Existing tests still work (check by running the test suite, e.g. from RStudio).
- [ ] Added tests (if you added functionality) or fixed existing test (if you fixed a bug).
- [x] Updated or expanded the documentation.
- [x] Updated release notes in `inst/NEWS.Rd` with a user-readable summary. Please, include references to relevant issues or PR discussions.
- [ ] Added your name to the contributors lists in the `DESCRIPTION` and `CITATION.cff` files.

### CODE REVIEW

**Comment by vincentvanhees** [comment]
@jhmigueles 
Could you add more clarification on "Create a new html vignette with the new chapter information."
Does pkgdown create these html files or is the developer expected to write those?
What are the steps the developer should do: Copy and edit a random html file from docs/articles?
I imagine there are a lot of things to consider, is there an tutorial by pkgdown on how to write these html files?

I just made one commit to try to improve some of the paragraphs, but this line about html I think is better if you do it.

**Comment by jhmigueles** [comment]
It can be done as any other vignette, either copying/pasting one of the other files or with `usethis::use_vignette()`. At least this is how I have done this in the past, there is nothing specific to `pkgdown` here, and there are no functions in `pkgdown` to create these vignettes. Do you want me to specify the copy/paste or the usethis option? Or both?

**Comment by jhmigueles** [comment]
I have expanded the documenation on how to contribute on the vignettes and github.io chapters following your feedback. Let me know if the instructions are clear now.

**Review by vincentvanhees — APPROVED** [review]
Thanks!

**Pull request merged**
