### PR TITLE
Update g.analyse.R

### PR DESCRIPTION
**Pull request by jhmigueles**
Hi Vincent,

You asked me to add the function complete.cases to the code and create a new pull request. I'm not sure if I got you, the function complete.cases belongs to the stats package, so I have included this to the code. Is that what you meant?

Jairo

### CODE REVIEW

**Comment by vincentvanhees** [comment]
Thanks Jairo,
The branch has a merge conflict. Can you resolve it?
It probably requires an explicit reference to stats, as in: stats::complete.cases().

Do you know how to build, check and test the package? It will be of great help if you could do this before making a pull request, as that would provide some reassurance that I can also easily upload it to CRAN. For example, it checks whether you provided documentation and are not using undeclared functions.

Next week I am working on GGIR related work again, so will then be able to help.
Vincent

**Comment by jhmigueles** [comment]
Hi Vincent,
I actualli don't know how to do it, but I will find thw way to do it. I will try to fix this the next week also, this week I am at a conference and it is difficult for me to find the time. Thank you for the suggestion.
Jairo

**Comment by vincentvanhees** [comment]
Hi Jairo, no problem. It will also be easier for you if you could check and fix these kind issues yourself.
Enjoy your conference!

**Comment by vincentvanhees** [comment]
Hi Jairo, there are various tutorials online, but in short:

In RStudio, create a project for your clone of the GGIR repository, then with the pull down menu 'Build' you can build/test/check the package.

From the (Linux) command line you can do the same via:
First cd inside the repository folder and do:
` R CMD build`
to build the package
`R CMD check`
to check the package
`R CMD test`
to test the package.

This weekend I spend some time writing more [tests](https://github.com/wadpac/GGIR/tree/expandtests). I will merge this into the master once I have managed to cover all key functionalities of the package... hopefully in the upcoming week.

The advantage of testing is that contributors can add code to the repository and easily check whether it breaks any of the existing functionalities.  Unfortunately, I did not do this right from the beginning in 2012 by which I now have some catching up to do. As you can see code coverage is currently 42%, so there is still a bit of work to do.

**Pull request closed without merging**
