### PR TITLE
GGIR logo added

### PR DESCRIPTION
**Pull request by vincentvanhees**
This pull requests add the new GGIR logo to the README file and to both vignettes.

In several places in the repository I have specified that the copyright of this logo lies with my company. I did this because the logo is now part of the branding of GGIR, by which it is not good if a variety of modified versions start to circulate online. Well, maybe I need to rethink this more, but for the time being I prefer to remain a bit more protective.

Please note that I have a full logo specification package offline, including: inverted and black-white versions, special image file types for printing the logo, and the specific color codes and font types.

### CODE REVIEW

**Comment by vincentvanhees** [comment]
tagging the corresponding issue #381

**Comment by m-patterson** [comment]
Do you think it would be better to put the logo at the top of the vignette, instead of after the table of contents?

image

**Comment by vincentvanhees** [comment]
Yes, and somehow I did not manage to get that to work the first time. I have now given it another try and found a solution.

As you will see I have moved the table of contents to the left of the screen such that it remains visible while you scroll down. This makes that the logo is directly visible when you open the page.

Additionally:
- I have now expanded the author list of the vignette. In this way it no longer looks as if I wrote the vignette on my own. I listed you, Jairo, Séverine and myself. We are the four people who have by far made the most significant contributions to GGIR. All other contributors made ad-hoc contributions and are not actively involved anymore. Séverine has not contributed as a programmer, but has played an important role over the years by testing GGIR and providing feedback on lots of aspects.
- I discovered that it is possible to use tabs in the vignette. I have now implemented this in the chapter "Inspecting the results" where I think it is a help addition.

**Comment by m-patterson** [comment]
That new format for the table of contents works really well!

**Pull request merged**
