### PR TITLE
fix xy coords error and annotation error in plot generation

### PR DESCRIPTION
**Pull request by m-patterson**
Update to visualization report generation
- fix xy coords error that was coming up now and again. It was due to elements [t1] not being updated properly on day 1 when there was less than 24hr worth of recordings.
- fix error in plotting sleeponset and wake annotations, when sleeponset was after midnight
- allow for multiple sleeponsets in one day
- update figure in vignette to show more data (2 days instead of 1 and more vig PA)

### CODE REVIEW

**Comment by vincentvanhees** [comment]
I am currently working on some files where sleep detection is problematic because of a lot non-wear time and/or people waking up after 6pm the next day. When I test your visualisation on those files the day number, name and date are not shown like they are in your new example image. So, these may be edge cases, but it would be good to make the code robust against such scenarios.

I am getting the following warnings. My suspicion is that the code gets stuck here and then terminates before it is able to add the date and day number:
```
Warning messages:
: In if (sleeponset_loc == 0 & wake_loc == 0) { ... :
  the condition has length > 1 and only the first element will be used
: In wake_loc:sleeponset_loc :
  numerical expression has 2 elements: only the first used
: In if (sleeponset_loc != 0) { ... :
  the condition has length > 1 and only the first element will be used
: In wake_loc:sleeponset_loc :
  numerical expression has 2 elements: only the first used
: In if (sleeponset_loc != 0) { ... :
  the condition has length > 1 and only the first element will be used
```

As you can see the code struggles with sleeponset_loc object ending up having a length larger than 2. Can you have a look at the code to see where this may go wrong?

I have the same issue when I apply GGIR from the master branch, so this issue already existed before this pull request. Thanks

**Comment by vincentvanhees** [comment]
... in the mean time I am working on checking that the part 4 and part 5 analysis generate meaningful results for those individuals. But for the plot5 code it seems good to check that it is impossible for objects like sleeponset_loc to have a large value than we expect it to have, regardless of the data that flows through it.

**Comment by vincentvanhees** [comment]
Could it be that pdf in US letter format versus A4 format is what is causing that you were unhappy with dimensions and that correcting for it affects the A4 format I see? I received a comment a long time ago that in the US these pdf are not formatted well. Maybe we need to explicitly code the pdf format (preferably A4) such that users everywhere can standard output?

**Comment by m-patterson** [comment]
Thanks for passing that along Vincent, I'll have a look at the
error. 
It must be due to the fact that now sleeponset_loc can be of length 2.
Thanks, Matt 

----- Original Message -----

**Comment by m-patterson** [comment]
hi Vincent,
Would it be possible to send me one of the de-identified files in
which this is causing a problem?    No worries if not.
I've gotten a bit crazy this week, but should be able to get to it
later in the week.
Thanks, Matt 

----- Original Message -----

**Comment by m-patterson** [comment]
I'm going to close this pull request, as I have more updates to include

**Pull request closed without merging**
