### PR TITLE
Add MAD to g.applymetrics

### PR DESCRIPTION
**Pull request by jhmigueles**

### CODE REVIEW

**Comment by vincentvanhees** [comment]
hi Jairo, good suggestion to add the MAD metric. I had a quick look at your code: It uses a loop through all the raw data to calculate the feature. This might be unnecessarily slow. Did you consider using `sapply()` for speeding up the code? Let me know if you need help.

**Comment by jhmigueles** [comment]
Hi Vincent,

In fact I wanted to improve the code as well as propose the changes 
necessaries in g.getmeta and g.part1 before to pull it. But I'm pretty 
new in Github and I pushed the wrong button.

Sorry for this, I will use sapply as you said, thanks for the 
suggestion =)

**Comment by vincentvanhees** [comment]
Hi Jairo, no problem, I understood. Do you think we can improve the name of the MAD metric to better reflect the calculation it does? To me 'mean amplitude deviation' sounds rather ambiguous. An amplitude is by definition a deviation, and it is not clear whether we are looking at the mean of the deviation or at the deviation in the mean amplitude. I think it should be fine to change the name as long as we clarify in the code and in future papers that the underlying calculation is the same as in MAD.

**Comment by jhmigueles** [comment]
So, do you suggest to call it simply Mean Amplitude? Maybe we can keep in the code the acronym proposed in the paper (MAD), to avoid confussion for the users, and change the name in the vignettes. What do you think? Also, I finished writing the code for g.applymetrics, g.getmeta, g.part1 and g.shell.GGIR.

Now, I think that it is also important to make possible to extract information from MAD such as mvpa thresholds and bouts. I have seen that you proposed an issue to make the rest of the functions independent of ENMO, is anyone working on that? If not, I can try it.

Do you prefer that I pull the changes now so you can revise them? or should I keep working in these thing and pull the changes when I finish?

**Comment by vincentvanhees** [comment]
Hi Jairo, It took me more than four years to do the research underlying the [2013 PLoSONE paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0061691) on the choice of aggregation metric for accelerometer data. In the absence of a convincing winner, we eventually made a pragmatic decision to ensure methodological consistency because PA research could not wait forever.

I am worried that making it too easy for GGIR users to choose their own acceleration metric will be a disaster for methodological consistency in PA research. The ENMO has now been used in over 20 non-methodological publications. I think we should only open up the rest of GGIR to another metric as long as there is no convincing evidence on the superiority of those other metrics. 

Doing just a lab study with MET as a reference values or looking at correlations between metrics is not enough to say anything about validity of the aggregation (MET is not a gold standard of acceleration quantification). Ideally, we need comparisons against gold standard reference acceleration of robots complemented by real life comparisons  against doubly labelled water like I did in 2013.

I am supportive of making GGIR part 1 and 2 functional to facilitate this kind of methodological research, but I am against doing the same for part 3, 4 and 5 at this moment, especially because part 3-5 go beyond just aggregating the data. Further, I think there are far more urgent research questions to be looked at than metric choice: e.g. the question of how to summarize the metric values once they are extracted.

For every metric being introduced in the literature there a separate branch of literature is started on sedentary thresholds for that metric, on MVPA thresholds for that metric and on sleep detection on the metric. This sounds extremely inefficient to me, because none of those papers will complement each other, PA researchers will not be able to compare their findings, and years of research time will be wasted on miscommunication because everyone will use a different metric. So, let's stick with enabling metric MAD part 1 and 2 for now to facilitate fundamental research, but not start confusing the literature with more metrics too soon.

**Comment by vincentvanhees** [comment]
We can clarify meaning of the metric in the documentation and its relation with metric MAD. I prefer to aim for meaningful metric abbreviations in the GGIR. I think the word amplitude is the most ambiguous part of the name MAD. Shouldn't it be MEND? Mean Euclidean Norm Deviation? This would then be in line with the rest of the metric names in GGIR.

**Comment by jhmigueles** [comment]
Hi Vincent, I get your point, it is totally fine with me to do part 1 and 2 functional for MAD (or RMEND), it is enough to make methodological research. About to increase the visibility of ENMO, have you though in develop an application or software to get ENMO and the derived measures? A lot of people keep using counts because is easier to extract the metrics and to apply cut-points in ActiLife than in R, at least in Spain we are just a few the researchers that use R. So, maybe a Shiny application could be a good start for this, the aim of this application would be only extract the data to use in epidemiological studies, I mean, not to extract a dataset such as metashort, but just the daysummary dataset, for those people not interested in mehodological questions, it would facilitate the use of ENMO.

Maybe you know, but the groud that developed MAD is promoting this metric, they are showing methods to easily get MAD, etc. This can be a disaster for methodological consistency as you said. So, a paper comparing metrics could aware from this problem. As well as get an easy way to use ENMO for those people not users of R.

And about the name: Actually, ENMO for example is also a rolling mean, you calculate ENMO and the calculate the mean per each epoch of the measurement period, this is a rolling mean, isn't it? Please correct me if I am wrong, I like statistics, but I'm not an expert. However, ENMO is not called RMENMO, I think for the name would be enough with END (Euclidean Norm Deviation), or maybe DEN (Deviation from the Euclidean Norm), just to facilitate the pronuntiation. Anyway, tell me what name you prefer and I'll apply it in the code.

**Comment by vincentvanhees** [comment]
Hi Miguel, I have very limited time for being involved in this. It may be easier if you first develop the functionality you want for your own research in your own fork and then later we can see whether it is worth merging it in with GGIR on CRAN. All I can do is from time to do review the issue posts and solve some minor bugs.

Metrics - Decisions about metrics should be driven by the science and that is what I try to do in a transparent way. I am not interested in ego battles about who's metric is most popular. I have not seen any convincing evidence for the superiority of any metric, which is why I am recommending the ENMO as a pragmatic approach as it was used in the earlier papers. [This](https://www.ncbi.nlm.nih.gov/pubmed/?term=27706241) paper supports that. There are much more important research questions to focus on. If there are scientists who start using a metric because it has been advertised to them then it is their responsibility to look critically at the underlying evidence and consequences for methodological consistency and not my responsibility.

Shiny - I have no interest in helping scientists for whom it is even too difficult to install R and copy paste the R-code from the package vignette. If they have no interest in putting even a small amount of effort in learning about GGIR then I think it is better for them to use commercial software services via GENEActiv or Actigraph instead. GGIR is not a production quality software, but only exists to make the research I have been involved in transparent and reproducible.

**Pull request closed without merging**
