### PR TITLE
modifications to issue622_LongGaps branch #522

### PR DESCRIPTION
**Pull request by vincentvanhees**
Hi @jhmigueles 

This PR aims to fix your issue622_LongGaps development branch for the long time gap imputation  as described in #522. 

These changes should enable epoch level imputation of large time gaps for both metashort and metalong objects.

- Imputation now happens inside g.getmeta with the help of g.imputeTimegaps as you nicely programmed.
- I reversed all changes to g.applymetrics (by copy-pasting the code from the master branch), because I think we should not mix the metric calculation code with time gap imputation code. Instead, by now having all of it in g.getmeta makes the code more compact and easy to skip for other sensor brands without timegaps. 
- The matrix extension step in g.getmeta now utilises the known total size of timegaps, such that we do not risk that metashort or metalong are too small.
- g.imputeTimegaps:
  - now takes argument `epochsize` instead of `ws3`. I prefer to avoid using `ws3` as function argument name, because it is not readable. I know I once introduced this a long time ago, but let's try to avoid it. Argument `epochsize` is a numeric vector of length two to carry both short and long epoch size. The long epoch size is used to define a long time gap as function of long epoch size. 
  - Now imputes all timegaps if no long timegaps are found, in your code this was not done. It only imputed timegaps if there was at least one long timegap.
- read.myacc.csv now also utilised this functionality.

My evaluation so far:
- All unit-tests now pass.
- I processed a large ActiGraph file with long time gaps and the output looks plausible now. Also my machine did not crash :)

Not done yet:
- Update NEWS.Rd

### CODE REVIEW

**Comment by vincentvanhees** [comment]
I have one more reflection on this:
Ideally we should move the time gap imputation from read.myacc.csv to g.getmeta just like we have for ActiGraph data. In that way all the time gap imputation work happens in one place. Also the read.myacc.csv function will then be simplified to just reading data which will ease maintenance. However, I cannot immediately oversee whether this poses challenges or problem? 

To not overload ourselves with work, we could treat this as a separate issue to be worked on later in the year...

**Comment by jhmigueles** [comment]
As we discussed, I have re-organized g.getmeta to take into account the imputation from one chunk to the next one (especially the imputation of the left over from previous chunk). I have also modified the tests and consciously made sure that the output from the test is what it should be.

Still to do:
- Update NEWS.Rd
- Moving imputation out of read.myacc.csv for adhoc files (the only concern I have is that resampling occurs after imputation, so we might need to also move the resampling out to g.getmeta).

**Comment by vincentvanhees** [comment]
The code looks good. It concerns me a little bit that we have been making a changes to unit tests and how objects `data` and `P` are dealt with. Even though I am able to follow the logic it feels that these are the kind of changes we should not be making frequently.

**Comment by vincentvanhees** [comment]
> Moving imputation out of read.myacc.csv for adhoc files (the only concern I have is that resampling occurs after imputation, so we might need to also move the resampling out to g.getmeta).

Let's postpone that for another time, and create a new issue for it. Let's first make sure the current work gets tested by the community.

**Comment by jhmigueles** [comment]
> these are the kind of changes we should not be making frequently

I agree, that's why I dedicated some extra time to make sure that the output was the expected. The change in the unit tests are due to this:

- In previous version, `S` (the left over from the previous chunk read), was determined as `S = as.matrix(data[(use + 1):LD,])`. 
- This probably was logic in the previous version, but after moving the `SWMT` object definition, in this version data is already shorter than `P` at this point. So, defining `S` from data and `LD` would make us skip a portion of the data from the chunk 2 onwards.
- To make sure this was behaving as expecting, I tried with several files, and calculated the number of expected epochs in metashort and metalong considering different sampling frequencies. Then I checked that metashort and metalong had the expected dimensions.

**Pull request merged**
