### PR TITLE
plot5 update

### PR DESCRIPTION
**Pull request by m-patterson**
- plot elements are adaptable to various short epoch sizes
- properly deal with noon to noon sleeponset / wake detection type
- allow for multiple wakes in one day
- update sleep/wake and activity annotations based on variable number of sleeponset and wake annotations

### CODE REVIEW

**Comment by vincentvanhees** [comment]
Thanks Matt. I have tried the following test scenarios with two different test files (A and B):

| Epoch length | Plot5 result |
| ----------- | ----------- |
| 5 sec | Works well with file A, but in file B it seems to be missing some onset and waking times and as a result it marks those entire days as part of the sleep period.  |
| 1 min | In terms of plotting proportions the plots look good for both files. Day numbers/names are not shown for file A and B. For file A I still get a warnings relating to the length of the object sleeponset_loc `the condition has length > 1 and only the first element will be used`This time I do not get the warnings related to object sleeponset_loc. For file B I do not get such warnings.  |

I am going to send you a copy of file A and B. I checked whether the type of sleep estimate guidance has any effect (sleep log or not) but this seems irrelevant.

**Comment by m-patterson** [comment]
Thanks for sending those tests over Vincent, I'll have a look at them to see what's going on.

**Comment by m-patterson** [comment]
Vincent, are you sure that you did your testing on the correct branch? The fact that day numbers / names aren't showing up with 60sec epoch makes me think you didn't run the tests with the right code (as this issue was fixed in the pull request). I had no issues with the plots when I ran both files at 5sec and 60sec short epoch. I have provided some screen shots below to show my plot5 results:

TestA / 5sec:
image

TestB / 5sec:
image

TestA / 60sec:
image

TestB / 60sec:
image

**Comment by vincentvanhees** [comment]
Thanks, visualisations look great. I will try again.

I followed the instructions here in the pull request when you click on "command line instructions" which then indicates that the following command should be used to checkout the code:
```
git checkout -b m-patterson-master master
git pull https://github.com/m-patterson/GGIR.git master
```

**Comment by m-patterson** [comment]
That seems like it should work, but I don't know for sure. I usually use fetch commands to the remote and then a pull.

You could double check that the code you're running has these lines in plot5 (near the bottom):
image

Particularly, the existence of the 'plot_loc' variable and then used to set the x location on the annotations on the next three lines.

**Pull request merged**
