### PR TITLE
Adding fragmentation metrics + basic light variables to GGIRpart5 output

### PR DESCRIPTION
**Pull request by vincentvanhees**
This is a large pull request mainly related to the addition of fragmentation metrics. I have been working on this in collaboration with Séverine Sabia and her team for the past year.  Additionally, this pull request also includes a few other updates that we considered relevant for our project.

Part of developing this we applied the new GGIR features to their 4000 GENEActiv recordings and we critically checked outliers, missing values, and variable correlations.

### 1. Fragmentation metrics
- New function [g.fragmentation](https://github.com/wadpac/GGIR/blob/issue195_fragmentation/R/g.fragmentation.R) calculates the fragmentation metrics for the waking segment of the day, so this is about physical activity and physical inactivity fragmentation. We are not calculating sleep fragmentation yet, implementing and checking the current functionality was already a lot of work and possibly some of the metrics used for waking hours are less informative for sleep, so it is better not to rush that, but it could be future project. Function g.fragmentation is [called from within g.part5](https://github.com/wadpac/GGIR/blob/issue195_fragmentation/R/g.part5.R#L757-L763).
- Correspondingly I have added [function documentation](https://github.com/wadpac/GGIR/blob/issue195_fragmentation/man/g.fragmentation.Rd) and a [new section](https://github.com/wadpac/GGIR/blob/issue195_fragmentation/vignettes/GGIR.Rmd#L777-L832) to the vignette on the fragmentation analysis, as well as some [guidance](https://github.com/wadpac/GGIR/blob/issue195_fragmentation/vignettes/GGIR.Rmd#L585-L597) on fragmentation metric names. To get you started the most important instruction is:

> When setting input argument as `frag.metrics="all"` GGIR part 5 will perform daytime behavioural fragmentation analysis. It is adviced to do this in combination with argument `part5_agg2_60seconds=TRUE` as that will aggregate the time series to 1 minute resolution as is common in behavioural fragmentation literature.

### 2. New bout metric
- While working on the fragmentation metrics we discovered that the bout metric is still not optimal, which becomes apparent when aggregating the data 1 minute resolution as we recommend for fragmentation analysis. The new [bout.metric is number 6](https://github.com/wadpac/GGIR/blob/issue195_fragmentation/R/g.getbout.R#L130-L198).
- I have improved the corresponding [unit test](https://github.com/wadpac/GGIR/blob/issue195_fragmentation/tests/testthat/test_ggetbout.R) to help check that we got it right this time.

### 3. Part 5 weekday and weekend aggregates.
- The user can now get these in the part 5 person-level summary by setting argument `week_weekend_aggregate.part5=TRUE`, default = FALSE.

### 4. Part 5 report on LUX information
- We are currently exploring ways of reporting the LUX (light) information at day and person level. At the moment this mainly works for GENEActiv data because that is the sensor user in our project. Although, we may be advancing this in the upcoming months I am adding this implementation to the master branch to let other people help test it. 

### 5. Setting maximum number of CPU cores to use.
- I have added argument `maxNcores` to control the maximum number of cores to be used in parallel processing mode. I noticed that this is relevant when working on a shared machines with hundreds of cores. See #417. By default GGIR will still use the maximum number of CPU cores.

Edit: I almost forgot, another addition is:

### 6. Intensity gradient now also in part 5.
- The intensity gradient was already calculated in part 2 over the full recording day, but now it is also calculated in part 5 for daytime (waking hours) only.

### CODE REVIEW

**Comment by m-patterson** [comment]
I ran this branch on a local test branch and it all seemed to have run fine up until Part 5, when it crashed and gave this error:
image

I am currently placing debug points to try to find where the error is and why it occurred, but if you guys (@vincentvanhees  @jhmigueles ) have any insight, please let me know. 

All these files processed fine with previous stable versions of GGIR.

**Comment by vincentvanhees** [comment]
Line 202 in function g.part4: `load(paste0(metadatadir,"/meta/basic/",fnames.ms1[selp]))`
should load the milestone data from part 1, which includes object `M`. This may be a good first step to check.

**Comment by m-patterson** [comment]
> Line 202 in function g.part5: `load(paste0(metadatadir,"/meta/basic/",fnames.ms1[selp]))`
> should load the milestone data from part 1, which includes object `M`. This may be a good first step to check.

@vincentvanhees Let me know if you want me to send you the file in which I'm having the problem

**Comment by vincentvanhees** [comment]
Yes, feel free to send me the file as that may indeed be the easiest route. I have been spending a lot of time testing this with GENEActiv files, so maybe there is just something tiny I overlooked.

**Comment by jhmigueles** [comment]
I got the same problem with actigraph files
image

**Comment by jhmigueles** [comment]
It run smooth on actigraph files now. I'm testing it on some axivity, geneactiv and movisens files, but it should be ok.

**Comment by m-patterson** [comment]
the updated branch is working well for me now

**Review by m-patterson — APPROVED** [review]
Working well

**Comment by m-patterson** [comment]
I am seeing some poor performance of the sleep detection with the branch. I haven't tested on my local test set for several months, so I'm not sure that this change was due to the current pull request or something before (I have some older test data that suggests it was from before). Either way, the sleep detection is not working as good as it used to. Generally, it seems that sleep-onset is being detected far too late. Here are some examples:
image

These incorrect sleep onset times are reflected in the part4 cleaned output, with two nights SptDuration incorrectly being labelled as 1.9 and 5 hours:
image

Here is another example of sleep onset times being too late:
image

The corresponding part4 cleaned data is also incorrect:
image

These are only 2 of 8 tests in the test set, so represents a fairly high frequency of error. Sleep onset was working properly on these tests after the GGIR 2.0 release, so I'll test backwards to see when the error came in.

**Comment by vincentvanhees** [comment]
Thanks Matt - Part 3 and part 4 are not changed in this pull request, so if there is a problem with sleep detection then I think it was introduced in an earlier update.

Just had a look, and I identified these PRs from the past 6 months that may be relevant:
https://github.com/wadpac/GGIR/pull/405
https://github.com/wadpac/GGIR/pull/403
https://github.com/wadpac/GGIR/pull/399
https://github.com/wadpac/GGIR/pull/392
https://github.com/wadpac/GGIR/pull/379
https://github.com/wadpac/GGIR/pull/374

**Comment by m-patterson** [comment]
> Thanks Matt - Part 3 and part 4 are not changed in this pull request, so if there is a problem with sleep detection then I think it was introduced in an earlier update.
> 
> Just had a look, and I identified these PRs from the past 6 months that may be relevant:
> #405
> #403
> #399
> #392
> #379
> #374

Thanks @vincentvanhees, I'll go through those updates in order to see where the issue crept in, using my local test-set

**Comment by vincentvanhees** [comment]
Sounds good @m-patterson 
Ok, I think you can skip #374 and #379 because they do not affect sleep estimates.
Further, #399 should only affect 1 day recordings.

**Comment by vincentvanhees** [comment]
Overview of all code changes between 7-12-2020 and current PR:
https://github.com/wadpac/GGIR/compare/6bbfc0a2cad4f0d316897495d0b865d437147630...issue195_fragmentation

I just went through them. The functions that changed and that may in one way or the other impact on sleep estimates are below. 
- R/g.detecmidnight.R
- R/g.part5.R <= probably not relevant
- R/g.part5.addfirstwake.R  <= probably not relevant
- R/g.part5.fixmissingnight.R
- R/g.sib.det.R <= probably not relevant
- R/g.sib.sum.R <= I restructured the code, but not clear what problem could be.

I have gone through them but do not spot any obvious suspicious changes.

**Comment by vincentvanhees** [comment]
@m-patterson for the "08_verisense" file you shared with me yesterday I do not see anything suspicious in the visual report. Only Day 9 may be considered, but this should be explained by non-wear during that night.

image


Can you send me a file for which you know that visual report does not look good now, but for which it did look good in the past?

**Comment by m-patterson** [comment]
> Can you send me a file for which you know that visual report does not look good now, but for which it did look good in the past?

@vincentvanhees, I've uploaded trial 07 to the same older and 02 is currently uploading, those were the example that I showed had an error in sleep onset detection.

**Comment by jhmigueles** [comment]
As for this pull request, it run well in all the files I tested from different brands.

**Comment by m-patterson** [comment]
branch is working correctly on my local test set, it was an error in my window size input that was causing the problem in sleep onset detection.

**Review by m-patterson — APPROVED** [review]

**Review by jhmigueles — APPROVED** [review]

**Pull request merged**
