### PR TITLE
Expansions to sleep functionality

### PR DESCRIPTION
**Pull request by vincentvanhees**
### Expansions to sleep functionality
1. Implementation of the Sadeh and Galland sleep detection algorithms (see #427). More specifically, I added the zero-crossing count calculation needed for these algorithms to `g.applymetrics`, and function `g.sib.det` now allows for chosing how sleep, I call it sustained inactivity bouts = SIB, should be detected: vanHees2015 (default), Sadeh1994, and Galland2012.
2. When working with hip-worn accelerometer data GGIR attempts to estimate time in bed, if argument `sensor.location` is set to "hip". For this the code uses the horizontal orientation (defined as: -45 < angle < 45) of the longitudinal sensor axis as indicator for potential lying time.. Next, it uses the last steps of the HDCZA algorithm to identify the longest lying episode in the day.  In the code this new algorithm is referred to as `"HorAngle"`. 
3. Function `g.sib.det` code has been restructured such that SPT, Time in Bed and SIB detection happen in newly created functions called: `HASIB` (Heuristic Algorithms for Sustained Inactivity Bout detection) and `HASPT` (Heuristic Algorithms for Sleep Period Time detection). I did this to improve the readability of function g.sib.det. As a result I was able to simplify the handling of single and multi-day recordings (see #398).
4. GGIR is now able to handle both the old basic sleeplog format and a more advanced sleeplog format which facilitates nap and nonwear entries by calendar date. See code updates to `g.loadlog` and `g.part4`. These self-reported naps and nonwear are now used in `g.part5`, where it is used to export the start and end times of the accelerometer-detected sustained inactivity bouts, as well as the start and end times of the self-reported naps and nonwear to csv report to aid nap analysis (see #418). For the moment it just stores the information, later this year I may expand this with complementary functionality to do actual nap behaviour analysis.

### Minor updates related to the above.
5. Part 4 is now able to handle time in bed diaries/algorithms, and if they are used it will automatically generate sleep latency and sleep efficiency estimates.
6. Part 4 report now includes guider estimates also in 'cleaned' report, previously these were only stored in the full report, but now the guider can also represent time in bed it makes sense to also show this to the user in the cleaner report.
7. WASO and NOA (Number of awakenings) added to the part 4 report
8. Work on GGIR vignette text, function documentation, and unit tests to reflect all these changes.
9. Effort made to shorten function g.part4 which is one of the longest functions in GGIR. I moved about 75 lines from g.part4 code to a newly created `g.part4_extractid`.

Checklist before merging:

- [x] Existing tests still work (check by running the test suite, e.g. from RStudio).
- [x] Added tests (if you added functionality) or fixed existing test (if you fixed a bug).
- [x] Updated or expanded the documentation.
- [x] Updated release notes in `inst/NEWS.Rd` with a user-readable summary. Please, include references to relevant issues or PR discussions.
- [x] Added your name to the contributors lists in the `DESCRIPTION` and `CITATION.cff` files.

### CODE REVIEW

**Comment by vincentvanhees** [comment]
I know it is summer time, and you all may be enjoying your summer break. So there is no major rush to this PR.

@l-k- this is the PR I announced in #398. Would you mind reviewing this? It comes with more code updates then you may be interested in, but it would be great if you could at least check that your issue relating to 1 night recordings has been addressed. I tried to send you a review request above, but somehow I could not select your GitHub tag l-k-.

@m-patterson These changes should have no impact on your default GGIR usage. All of this relates to new optional variations to how GGIR can be used.

@jhmigueles I remember you worked with ActiGraph's implementation of the Sadeh algorithm. You may be interested to know that GGIR now also has an  implementation. If you could try this out on your data and let me know if estimates look plausible that would be great.

**Comment by l-k-** [comment]
@vincentvanhees -- got the notification, very happy to review this!

**Comment by m-patterson** [comment]
On a local test set, I received this error at part4 of the algorithm:
image

The config.csv file was not create, but here are my settings used:
image
image

On another note, when I source functions, I add these functions in order to run the external function calling:
image

However, there seemed to be an error with the 'resample' function:
image

and here:

image

**Comment by vincentvanhees** [comment]
> error at part4 of the algorithm:

Thanks, this should be fixed now. I forgot to declare a default value for object `addlegend` at the top, in case `do.visual = FALSE`.

> config.csv file was not created

I am not able to reproduce this. The config file is created in `g.shell.GGIR`. So, if this function is run it should normally produce the file. Let me know if it keeps doing this.

> However, there seemed to be an error with the 'resample' function:

Thanks for spotting. I previously expanded the resample function to have the option to do nearest neighbor interpolation as opposed to linear interpolation (still the default). This to enable research on the possible role of the resampling/interpolation approach. The nearest neighbor algorithm uses std::round which only works with C++11. I have no rewritten the resample.cpp function to avoid this dependency on C++11.

**Comment by m-patterson** [comment]
The changes work for me, everything looks good now

**Comment by m-patterson** [comment]
All working well now

**Review by m-patterson — APPROVED** [review]

**Comment by m-patterson** [comment]
Not sure if this is only a problem local to my machine, but when I try to run .cwa files on this branch I get the following error:
image

The code works fine when I run my local Verisense files, which are saved as .csv

**Comment by vincentvanhees** [comment]
I am merging this pull request now. It has successfully been tested in four different datasets, which led to various minor correction. So, it is time for this to be part of a GitHub release.

**Pull request merged**
