### PR TITLE
Plot5 update

### PR DESCRIPTION
**Pull request by m-patterson**
Pull request to replace the 24-hr plots in the plot5 function. 

The update shows the following annotations that come out of GGIR:
- sleeponset time
- wake time
- SPT window - sleep periods
- SPT window - wake periods
- daytime inactivity
- light PA bouts (10min, 80% bout criteria)
- moderate PA bouts (10min, 80%)
- vigorous PA bouts (10min, 80%)
- nonwear detection

### CODE REVIEW

**Comment by vincentvanhees** [comment]
... I tried to [commit](https://github.com/wadpac/GGIR/commit/5bd73d7d4e4fcc6a7d0442e468e122bee9f238a3) my fixes to the errors Travis encountered, but this seems to have resulted in a new branch in the wadpac/GGIR repository. I will have a look how I can commit directly to this PR.

**Comment by vincentvanhees** [comment]
Hi Matt,
I seems the only way for me to make commits to your pull request is if I had access to your repository. Possible solutions:
1. We merge my new branch with a copy of this PR into the GGIR master, it will still include your commit history, so no information is lost.
2. You manually copy the changes I made (see link above) to your pull request and update this pull request.
3. You allow me to commit to your repo.

Option 1 is probably the easiest. Agree? If yes, I can create a pull request for that branch and you can double check that you are happy with the minor changes. Note that you also have commit rights to wadpac/GGIR so it should be easy for you to make edits there.

Some comment on the PR itself:
- Did you merge the sustained inactivity bouts during the day with the rest of inactivity? I think that is ok for now as the plot would get too crowded otherwise.
- Using yellow twice may cause confusion. Could light blue be an option to represent light PA?
Cheers, Vincent

**Comment by m-patterson** [comment]
hey Vincent, I think it will be best to do option 2 - I'll get the latest updates from master, then put in the plotting updates and then create a new pull request.

Here are the answers to your questions:
1. Inactivity comes from a lack of any light / mod / vig PA. First, 10min bouts of LPA and MVPA (80% boutcriter and thresholds from whichever thresholds were set in the calling of GGIR) are searched for. IF, it is daytime and no light, mod or vig PA was found, then the period is labelled as daytime inactivity in the plot.
2. Agreed, I'll have a look at trying to make the colours more distinct. They are actually quite different colours, but becuase I'm using a high alpha value, it is making them look very similar. The alpha is necessary to make sure that we can see through the box to the data underneath.

**Comment by vincentvanhees** [comment]
thanks

**Pull request closed without merging**
