### PR TITLE
Issue689 tail expansion

### LINKED ISSUE #689: Limit tail_expansion_max_hours to 5 hours max
- [ ] It seems argument `tail_expansion_max_hours` makes it too easy for researchers to fake a long recording length and get biased results without even realising it. The documentation already warns about this, but documentation alone is not possibly enough. I think we should constrain `tail_expansion_max_hours` to a maximum of 5 hours. This means that if the assumption is made that the participant fell asleep on or before 7pm on the last recording day then synthetic data is appended if the recording ends after 7pm. Users will be prohibited from making this kind of assumption for any time-point earlier in the day.
- [ ] I believe I checked the functionality thoroughly, but it may be good to check again that the code excludes the last recording day if it ends at 6.55pm and not when it ends at 7.05pm.

### PR DESCRIPTION
**Pull request by jhmigueles**
Fixes #689 
Here a summary of this PR:
- `expand_tail_max_hours` now expects a time (in hours) at which the recording should end (or later) to expand the metashort and metalong data frames with synthetic data.
- The expanded time now is ignored in all the reports and visualizations (including visualisation_sleep.pdf and visualreports).
- Documentation of this argument is updated.

Things that might be improved:
-  I have been thinking about changing the name of this argument to make clear that it expects a time in hours, but I could not think of any good name. Any suggestion?
- Should we add any warning if the users introduce an unrealistic time for this? e.g., `expand_tail_max_hours = 16`
- I could work on a test for this functionality, let me know if you think this is important.
- I have tried to make all the changes only `if (length(tail_expansion_log) != 0)`, so that it does not affect the normal processing when this function is turned off (but it might be good if you double-check this).

Checklist before merging:

- [x] Existing tests still work (check by running the test suite, e.g. from RStudio).
- [ ] Added tests (if you added functionality) or fixed existing test (if you fixed a bug).
- [x] Updated or expanded the documentation.
- [x] Updated release notes in `inst/NEWS.Rd` with a user-readable summary. Please, include references to relevant issues or PR discussions.
- [ ] Added your name to the contributors lists in the `DESCRIPTION` and `CITATION.cff` files.

### CODE REVIEW

**Comment by vincentvanhees** [comment]
Hi Jairo, I have a test file that starts on day 1 (Wednesday) at 6:15am and ends on day 4 (Saturday) at 22.59:55pm, so based on the master branch with default argument settings I get:

- 4 days in the part2_daysummary (Wednesday, Thursday, Friday, Saturday)
- 3 nights in part4_nightsummary (Wednesday-Thursday, Thursday-Friday, Friday-Saturday)
- 2 windows in part5_daysummary_MM (Thursday and Friday)
- 2 windows in part5_daysummary_WW  (wakeup Thursday - wakeup Friday, wakeup Friday - wakeup Saturday)

Once I set `expand_tail_max_hours = 3` when still using the master branch I get the same result which is not what I expect, because I expect one extra window in both part5_daysummary reports now our Saturday has a sleep estimate.

I get the same result when I run your branch with `expand_tail_max_hours = 21`, so I am wondering whether the master branch itself is already not providing the functionality we expect.

Does it work for you? Can you see what I am doing wrong?

**Comment by jhmigueles** [comment]
Hi Vincent, in the new branch, the expanded time is used for the determination of the latest SPT window, but then it is ignored in reports and visualizations. I did this because this is madeup data that was risky to be included as extra non-measured inactivity or sleep in reports. So, the time is imputed, it is used for the determination of the latest SPT as expected, but then, this expanded time is ignored in reports and it is not represented in the visualizations. Does that make sense?

**Comment by vincentvanhees** [comment]
My concern is about the part5 csv reports. The main reason to implement the expansion is to trigger the calculation of the last SPT window and to get the last day in the part5 csv report.

I agree that it should not be in the visualisation. Similarly, it should not be in the part 2 and part 4 reports.

**Comment by vincentvanhees** [comment]
So, I do not want the last artificial SPT to be reported in the part 4 or part 5 reports. I only want to use it to estimate the end of the waking hours of the last day, and these wakehour estimates should then be included in the part 5 csv report.

**Comment by vincentvanhees** [comment]
@jhmigueles note that there may be nothing wrong with your PR, my problem is that I do not seem to be able to replicate the expected functionality with both the master branch and with this branch and I was wondering whether it works for you.

**Comment by jhmigueles** [comment]
Are you looking at the full or the clean reports? Just thinking that for the clean reports, the last window in MM would be excluded because it has less than 23 recorded hours (from 0:00:00 to 22:59:55), and for WW this last window will never be included because there is not a wakeup time for the last SPT window, right?

**Comment by jhmigueles** [comment]
Everything done here, I included warnings and error messages and they work as they should. I also included a test for this functionality (testing that warnings and errors run when they should, and that time is expanded and properly handled in reports)

**Pull request merged**
